import { getHomeData, getTrending } from '@/lib/api';
import MovieCard from '@/components/MovieCard';
import Navbar from '@/components/Navbar';
import { Column, Drama } from '@/types';
import { Flame, Star } from 'lucide-react';
import Link from 'next/link';

export const revalidate = 3600;

export default async function Home() {
  const [homeColumns, trending] = await Promise.all([
      getHomeData(),
          getTrending()
            ]);

              const heroMovie = trending[0];

                return (
                    <main className="min-h-screen pb-20 bg-[#050505] text-gray-100">
                          <Navbar />

                                {heroMovie && (
                                        <div className="relative w-full h-[60vh] md:h-[80vh]">
                                                  <div 
                                                              className="absolute inset-0 bg-cover bg-center opacity-60"
                                                                          style={{ backgroundImage: `url(${heroMovie.coverWap || heroMovie.cover})` }}
                                                                                    />
                                                                                              <div className="absolute inset-0 bg-gradient-to-t from-[#050505] via-[#050505]/40 to-transparent" />
                                                                                                        
                                                                                                                  <div className="relative z-10 h-full flex flex-col justify-end px-4 lg:px-12 pb-12 max-w-4xl">
                                                                                                                              <span className="px-3 py-1 mb-4 text-xs font-bold text-black bg-white rounded-full w-fit">
                                                                                                                                            #1 TRENDING
                                                                                                                                                        </span>
                                                                                                                                                                    <h1 className="text-4xl md:text-6xl font-extrabold text-white mb-4 drop-shadow-2xl">
                                                                                                                                                                                  {heroMovie.bookName}
                                                                                                                                                                                              </h1>
                                                                                                                                                                                                          <p className="text-gray-300 text-sm md:text-lg line-clamp-3 mb-6 max-w-2xl">
                                                                                                                                                                                                                        {heroMovie.introduction}
                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                <Link 
                                                                                                                                                                                                                                                              href={`/drama/${heroMovie.bookId}`} 
                                                                                                                                                                                                                                                                            className="px-8 py-3 bg-purple-600 hover:bg-purple-700 text-white font-bold rounded-xl w-fit flex items-center gap-2"
                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                      <Flame className="w-5 h-5" /> Tonton Sekarang
                                                                                                                                                                                                                                                                                                                  </Link>
                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                                                                <div className="px-4 lg:px-8 space-y-12 -mt-10 relative z-20">
                                                                                                                                                                                                                                                                                                                                                        <section>
                                                                                                                                                                                                                                                                                                                                                                  <div className="flex items-center gap-2 mb-6">
                                                                                                                                                                                                                                                                                                                                                                              <Star className="w-6 h-6 text-yellow-500 fill-yellow-500" />
                                                                                                                                                                                                                                                                                                                                                                                          <h2 className="text-2xl font-bold text-white">Sedang Hangat</h2>
                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                              <div className="grid grid-cols-3 sm:grid-cols-4 md:grid-cols-5 lg:grid-cols-6 gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                          {trending.slice(1, 7).map((drama: any) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                        <MovieCard key={drama.bookId} data={drama} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {homeColumns.map((col: Column) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <section key={col.columnId}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h2 className="text-xl font-bold text-white mb-6 border-l-4 border-purple-600 pl-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {col.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="grid grid-cols-3 sm:grid-cols-4 md:grid-cols-5 lg:grid-cols-6 gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {col.bookList.map((drama) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <MovieCard key={drama.bookId} data={drama} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                