"use client";

import { useState, useEffect } from 'react';
import Navbar from '@/components/Navbar';
import MovieCard from '@/components/MovieCard';
import { Loader2 } from 'lucide-react';
import { getHomeData } from '@/lib/api';

// Kita buat tipe data SENDIRI disini biar tidak tergantung file lain
interface SimpleDrama {
  bookId: string;
    bookName: string;
      cover: string;
        coverWap: string;
        }

        export default function Home() {
          const [columns, setColumns] = useState<any[]>([]);
            const [loading, setLoading] = useState(true);

              useEffect(() => {
                  async function init() {
                        try {
                                console.log("Mengambil data...");
                                        const data = await getHomeData();
                                                
                                                        // JIKA API KOSONG/GAGAL, KITA PAKAI DATA PALSU BIAR WEB GAK KOSONG
                                                                if (!data || data.length === 0) {
                                                                           console.log("API Kosong, pakai data backup");
                                                                                      setColumns([
                                                                                                   {
                                                                                                                  title: "Trending (Mode Offline/Backup)",
                                                                                                                                 bookList: [
                                                                                                                                                  { bookId: "1", bookName: "Contoh Drama 1", cover: "https://placehold.co/300x450/purple/white?text=Drama+1" },
                                                                                                                                                                   { bookId: "2", bookName: "Contoh Drama 2", cover: "https://placehold.co/300x450/black/white?text=Drama+2" },
                                                                                                                                                                                    { bookId: "3", bookName: "Contoh Drama 3", cover: "https://placehold.co/300x450/blue/white?text=Drama+3" },
                                                                                                                                                                                                   ]
                                                                                                                                                                                                                }
                                                                                                                                                                                                                           ]);
                                                                                                                                                                                                                                   } else {
                                                                                                                                                                                                                                              setColumns(data);
                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                            } catch (e) {
                                                                                                                                                                                                                                                                    console.error("Error:", e);
                                                                                                                                                                                                                                                                          } finally {
                                                                                                                                                                                                                                                                                  setLoading(false);
                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                init();
                                                                                                                                                                                                                                                                                                  }, []);

                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                        <div className="min-h-screen bg-[#050505] text-white font-sans">
                                                                                                                                                                                                                                                                                                              <Navbar />
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                          {loading ? (
                                                                                                                                                                                                                                                                                                                                  <div className="h-screen flex flex-col items-center justify-center gap-4">
                                                                                                                                                                                                                                                                                                                                            <Loader2 className="w-10 h-10 animate-spin text-purple-600" />
                                                                                                                                                                                                                                                                                                                                                      <p className="text-gray-500 text-sm">Sedang memuat drama...</p>
                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                    ) : (
                                                                                                                                                                                                                                                                                                                                                                            <div className="pt-24 pb-20 px-4 max-w-7xl mx-auto">
                                                                                                                                                                                                                                                                                                                                                                                      {/* JUDUL HALAMAN (Biar kelihatan webnya hidup) */}
                                                                                                                                                                                                                                                                                                                                                                                                <div className="mb-8 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                            <h1 className="text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-purple-400 to-pink-600">
                                                                                                                                                                                                                                                                                                                                                                                                                          DramaBox Free
                                                                                                                                                                                                                                                                                                                                                                                                                                      </h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-gray-400 text-sm mt-2">Nonton Gratis Tanpa Iklan</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* DAFTAR DRAMA */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="space-y-12">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {columns.map((col: any, idx: number) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div key={idx}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2 className="text-xl font-bold mb-4 border-l-4 border-purple-600 pl-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {col.title || "Daftar Drama"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="grid grid-cols-3 sm:grid-cols-4 md:grid-cols-5 lg:grid-cols-6 gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {col.bookList?.map((drama: any) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // @ts-ignore
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <MovieCard key={drama.bookId || Math.random()} data={drama} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                