// @ts-nocheck
"use client";

import { useState, useEffect } from 'react';
import { getHomeData } from '@/lib/api';
import MovieCard from '@/components/MovieCard';
import Navbar from '@/components/Navbar';
import { Loader2 } from 'lucide-react';

// HAPUS IMPORT COLUMN YANG BIKIN ERROR.
// Kita pakai 'any' saja biar Vercel tidak rewel.

export default function Home() {
  const [columns, setColumns] = useState<any[]>([]); 
    const [loading, setLoading] = useState(true);

      useEffect(() => {
          async function init() {
                  try {
                              const data = await getHomeData();
                                          // Pastikan data selalu array biar gak blank
                                                      setColumns(Array.isArray(data) ? data : []);
                                                              } catch (e) {
                                                                          console.error("Gagal ambil data home:", e);
                                                                                  } finally {
                                                                                              setLoading(false);
                                                                                                      }
                                                                                                          }
                                                                                                              init();
                                                                                                                }, []);

                                                                                                                  return (
                                                                                                                      <div className="min-h-screen bg-[#050505] text-white font-sans">
                                                                                                                            <Navbar />
                                                                                                                                  
                                                                                                                                        {loading ? (
                                                                                                                                                 <div className="h-screen flex items-center justify-center">
                                                                                                                                                             <Loader2 className="w-10 h-10 animate-spin text-purple-600" />
                                                                                                                                                                      </div>
                                                                                                                                                                            ) : (
                                                                                                                                                                                    <div className="pb-20 pt-20">
                                                                                                                                                                                              <div className="px-4 mb-8 text-center">
                                                                                                                                                                                                           <h1 className="text-3xl md:text-5xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-purple-400 to-pink-600">
                                                                                                                                                                                                                           DramaBox Free
                                                                                                                                                                                                                                        </h1>
                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                            <div className="px-4 max-w-7xl mx-auto space-y-10">
                                                                                                                                                                                                                                                                        {columns.map((col: any, index: number) => (
                                                                                                                                                                                                                                                                                      <div key={index}>
                                                                                                                                                                                                                                                                                                      {col.bookList && col.bookList.length > 0 && (
                                                                                                                                                                                                                                                                                                                        <>
                                                                                                                                                                                                                                                                                                                                            <h2 className="text-lg md:text-xl font-bold mb-4 flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                    <span className="w-1 h-6 bg-purple-600 rounded-full"></span>
                                                                                                                                                                                                                                                                                                                                                                                            {col.title}
                                                                                                                                                                                                                                                                                                                                                                                                                </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="grid grid-cols-3 sm:grid-cols-4 md:grid-cols-5 lg:grid-cols-6 gap-3 md:gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                          {col.bookList.map((drama: any) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <MovieCard key={drama.bookId} data={drama} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      