"use client";

import { useEffect, useState } from 'react';
import { getDramaDetail, getAllEpisodes } from '@/lib/api';
import { DramaDetail, Episode } from '@/types';
import { ChevronLeft, Info, List, Loader2 } from 'lucide-react';
import Link from 'next/link';

export default function DramaPlayer({ params }: { params: { bookId: string } }) {
  const [detail, setDetail] = useState<DramaDetail | null>(null);
    const [episodes, setEpisodes] = useState<Episode[]>([]);
      const [currentEp, setCurrentEp] = useState<Episode | null>(null);
        const [videoUrl, setVideoUrl] = useState<string>('');
          const [loading, setLoading] = useState(true);

            // Unpack params (Next.js 15 requirement fix)
              const bookId = params.bookId;

                useEffect(() => {
                    async function init() {
                          try {
                                  const [d, e] = await Promise.all([
                                            getDramaDetail(bookId),
                                                      getAllEpisodes(bookId)
                                                              ]);
                                                                      setDetail(d);
                                                                              setEpisodes(e);
                                                                                      if (e && e.length > 0) selectEpisode(e[0]);
                                                                                            } catch (err) { console.error(err); } 
                                                                                                  finally { setLoading(false); }
                                                                                                      }
                                                                                                          init();
                                                                                                            }, [bookId]);

                                                                                                              const selectEpisode = (ep: Episode) => {
                                                                                                                  setCurrentEp(ep);
                                                                                                                      let bestUrl = "";
                                                                                                                          if (ep.cdnList) {
                                                                                                                                  for (const cdn of ep.cdnList) {
                                                                                                                                              if (cdn.videoPathList?.length > 0) {
                                                                                                                                                              const sorted = [...cdn.videoPathList].sort((a, b) => b.quality - a.quality);
                                                                                                                                                                              bestUrl = sorted[0].videoPath; 
                                                                                                                                                                                              break;
                                                                                                                                                                                                          }
                                                                                                                                                                                                                  }
                                                                                                                                                                                                                      }
                                                                                                                                                                                                                          setVideoUrl(bestUrl);
                                                                                                                                                                                                                            };

                                                                                                                                                                                                                              if (loading) return <div className="min-h-screen bg-black flex items-center justify-center text-purple-500"><Loader2 className="animate-spin" /></div>;
                                                                                                                                                                                                                                if (!detail) return <div className="min-h-screen bg-black text-white p-10">Drama tidak ditemukan.</div>;

                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                      <div className="min-h-screen bg-[#050505] text-gray-100">
                                                                                                                                                                                                                                            {/* HEADER & PLAYER */}
                                                                                                                                                                                                                                                  <div className="sticky top-0 z-50 bg-black w-full shadow-2xl">
                                                                                                                                                                                                                                                          <div className="absolute top-0 left-0 w-full p-4 flex items-center gap-4 bg-gradient-to-b from-black/80 to-transparent z-20 pointer-events-none">
                                                                                                                                                                                                                                                                    <Link href="/" className="pointer-events-auto bg-white/10 p-2 rounded-full backdrop-blur-md">
                                                                                                                                                                                                                                                                                <ChevronLeft className="w-6 h-6 text-white" />
                                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                                    <h1 className="font-bold text-white text-lg line-clamp-1">{detail.book.bookName}</h1>
                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                    <div className="w-full aspect-video md:h-[60vh] bg-black flex items-center justify-center">
                                                                                                                                                                                                                                                                                                                              {videoUrl ? (
                                                                                                                                                                                                                                                                                                                                          <video key={videoUrl} controls autoPlay playsInline className="w-full h-full object-contain" poster={currentEp?.chapterImg}>
                                                                                                                                                                                                                                                                                                                                                        <source src={videoUrl} type="video/mp4" />
                                                                                                                                                                                                                                                                                                                                                                    </video>
                                                                                                                                                                                                                                                                                                                                                                              ) : <div className="text-gray-500">Video tidak tersedia</div>}
                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                  {/* INFO & EPISODES */}
                                                                                                                                                                                                                                                                                                                                                                                                        <div className="max-w-5xl mx-auto p-4 space-y-6">
                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                          <h1 className="text-2xl font-bold text-white mb-2">{detail.book.bookName}</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex gap-2 mb-4 text-xs">
                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="bg-purple-600 text-white px-2 py-1 rounded font-bold">GRATIS</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="bg-gray-800 text-gray-300 px-2 py-1 rounded">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Ep {currentEp?.chapterIndex !== undefined ? currentEp.chapterIndex + 1 : 1}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="bg-[#111] p-4 rounded-xl border border-white/5 text-sm text-gray-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {detail.book.introduction}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex items-center gap-2 mb-4 text-white font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <List className="w-5 h-5 text-purple-500" /> Daftar Episode
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="grid grid-cols-4 sm:grid-cols-6 md:grid-cols-8 gap-2 max-h-[500px] overflow-y-auto pr-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {episodes.map((ep) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    key={ep.chapterId}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={() => selectEpisode(ep)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className={`p-3 rounded-lg border text-sm font-bold transition-all ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      currentEp?.chapterId === ep.chapterId 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ? 'bg-purple-600 border-purple-500 text-white' 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          : 'bg-[#151515] border-gray-800 text-gray-400'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {ep.chapterIndex + 1}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                