"use client";

import { use, useEffect, useState } from 'react';
import { getDramaDetail, getAllEpisodes } from '@/lib/api';
import { DramaDetail, Episode } from '@/types';
import { ChevronLeft, List, Loader2, Play } from 'lucide-react';
import Link from 'next/link';

// Next.js 15: params adalah Promise
export default function DramaPlayer({ params }: { params: Promise<{ bookId: string }> }) {
  // UNWRAP PARAMS (Wajib di Next.js 15)
    const resolvedParams = use(params);
      const bookId = resolvedParams.bookId;

        const [detail, setDetail] = useState<DramaDetail | null>(null);
          const [episodes, setEpisodes] = useState<Episode[]>([]);
            const [currentEp, setCurrentEp] = useState<Episode | null>(null);
              const [videoUrl, setVideoUrl] = useState<string>('');
                const [loading, setLoading] = useState(true);

                  useEffect(() => {
                      async function init() {
                            try {
                                    const [d, e] = await Promise.all([
                                              getDramaDetail(bookId),
                                                        getAllEpisodes(bookId)
                                                                ]);
                                                                        setDetail(d);
                                                                                setEpisodes(e);
                                                                                        if (e && e.length > 0) selectEpisode(e[0]);
                                                                                              } catch (err) { console.error(err); } 
                                                                                                    finally { setLoading(false); }
                                                                                                        }
                                                                                                            init();
                                                                                                              }, [bookId]);

                                                                                                                const selectEpisode = (ep: Episode) => {
                                                                                                                    setCurrentEp(ep);
                                                                                                                        let bestUrl = "";
                                                                                                                            if (ep.cdnList) {
                                                                                                                                    for (const cdn of ep.cdnList) {
                                                                                                                                                if (cdn.videoPathList?.length > 0) {
                                                                                                                                                                const sorted = [...cdn.videoPathList].sort((a, b) => b.quality - a.quality);
                                                                                                                                                                                bestUrl = sorted[0].videoPath; 
                                                                                                                                                                                                break;
                                                                                                                                                                                                            }
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                            setVideoUrl(bestUrl);
                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                if (loading) return <div className="min-h-screen bg-black flex items-center justify-center text-purple-500"><Loader2 className="w-10 h-10 animate-spin" /></div>;
                                                                                                                                                                                                                                  if (!detail) return <div className="min-h-screen bg-black text-white p-10 flex flex-col items-center justify-center"><span>Drama tidak ditemukan (ID: {bookId})</span><Link href="/" className="mt-4 text-purple-500 underline">Kembali ke Home</Link></div>;

                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                        <div className="min-h-screen bg-[#0a0a0a] text-gray-100 font-sans">
                                                                                                                                                                                                                                              {/* HEADER & PLAYER */}
                                                                                                                                                                                                                                                    <div className="sticky top-0 z-50 bg-black w-full shadow-2xl border-b border-white/10">
                                                                                                                                                                                                                                                            <div className="absolute top-0 left-0 w-full p-4 flex items-center gap-4 z-20 pointer-events-none">
                                                                                                                                                                                                                                                                      <Link href="/" className="pointer-events-auto bg-black/50 hover:bg-purple-600 p-2 rounded-full backdrop-blur-md transition-all">
                                                                                                                                                                                                                                                                                  <ChevronLeft className="w-6 h-6 text-white" />
                                                                                                                                                                                                                                                                                            </Link>
                                                                                                                                                                                                                                                                                                      <h1 className="font-bold text-white text-lg line-clamp-1 drop-shadow-md">{detail.book.bookName}</h1>
                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                      <div className="w-full aspect-video md:h-[70vh] bg-black flex items-center justify-center relative group">
                                                                                                                                                                                                                                                                                                                                {videoUrl ? (
                                                                                                                                                                                                                                                                                                                                            <video key={videoUrl} controls autoPlay playsInline className="w-full h-full object-contain" poster={currentEp?.chapterImg}>
                                                                                                                                                                                                                                                                                                                                                          <source src={videoUrl} type="video/mp4" />
                                                                                                                                                                                                                                                                                                                                                                      </video>
                                                                                                                                                                                                                                                                                                                                                                                ) : <div className="text-gray-500 flex flex-col items-center"><Play className="w-12 h-12 mb-2 opacity-50"/>Video tidak tersedia</div>}
                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                    {/* INFO & EPISODES */}
                                                                                                                                                                                                                                                                                                                                                                                                          <div className="max-w-6xl mx-auto p-4 md:p-8 space-y-8">
                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                            <h1 className="text-3xl md:text-4xl font-extrabold text-white mb-3">{detail.book.bookName}</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex flex-wrap gap-3 mb-6 text-xs md:text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="bg-purple-600 text-white px-3 py-1 rounded-full font-bold shadow-lg shadow-purple-900/20">GRATIS</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="bg-gray-800 text-gray-300 px-3 py-1 rounded-full border border-white/10">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Episode {currentEp?.chapterIndex !== undefined ? currentEp.chapterIndex + 1 : 1}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {detail.book.tags?.map(tag => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <span key={tag} className="bg-gray-800 text-gray-400 px-3 py-1 rounded-full border border-white/5">{tag}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <div className="bg-[#111] p-6 rounded-2xl border border-white/5 text-gray-400 leading-relaxed shadow-inner">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <h3 className="text-white font-bold mb-2 text-sm uppercase tracking-wider opacity-70">Sinopsis</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           {detail.book.introduction}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <div className="flex items-center gap-2 mb-4 text-white font-bold text-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <List className="w-6 h-6 text-purple-500" /> Daftar Episode
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <div className="grid grid-cols-4 sm:grid-cols-6 md:grid-cols-8 lg:grid-cols-10 gap-3 max-h-[500px] overflow-y-auto pr-2 custom-scrollbar">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           {episodes.map((ep) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         key={ep.chapterId}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         onClick={() => selectEpisode(ep)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         className={`aspect-square flex items-center justify-center rounded-xl text-sm font-bold transition-all transform hover:scale-105 ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           currentEp?.chapterId === ep.chapterId 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ? 'bg-gradient-to-br from-purple-600 to-indigo-600 text-white shadow-lg shadow-purple-500/30 ring-2 ring-purple-400' 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               : 'bg-[#1a1a1a] hover:bg-[#252525] text-gray-400 border border-white/5'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             {ep.chapterIndex + 1}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     