// @ts-nocheck
"use client";

import { use, useEffect, useState } from 'react';
import { getDramaDetail, getAllEpisodes } from '@/lib/api';
import { ChevronLeft, List, Play } from 'lucide-react';
import Link from 'next/link';

export default function DramaPlayer({ params }) {
  // UNWRAP PARAMS (Wajib untuk Next.js 15)
    const unwrappedParams = use(params);
      const bookId = unwrappedParams.bookId;

        const [detail, setDetail] = useState(null);
          const [episodes, setEpisodes] = useState([]);
            const [currentEp, setCurrentEp] = useState(null);
              const [videoUrl, setVideoUrl] = useState('');
                const [loading, setLoading] = useState(true);

                  useEffect(() => {
                      if (!bookId) return;
                          
                              async function init() {
                                    try {
                                            const [d, e] = await Promise.all([
                                                      getDramaDetail(bookId),
                                                                getAllEpisodes(bookId)
                                                                        ]);
                                                                                setDetail(d);
                                                                                        setEpisodes(e || []);
                                                                                                
                                                                                                        // Auto play episode 1
                                                                                                                if (e && e.length > 0) selectEpisode(e[0]);
                                                                                                                      } catch (err) {
                                                                                                                              console.error("Gagal memuat drama:", err);
                                                                                                                                    } finally {
                                                                                                                                            setLoading(false);
                                                                                                                                                  }
                                                                                                                                                      }
                                                                                                                                                          init();
                                                                                                                                                            }, [bookId]);

                                                                                                                                                              const selectEpisode = (ep) => {
                                                                                                                                                                  setCurrentEp(ep);
                                                                                                                                                                      // Logika mencari kualitas video terbaik
                                                                                                                                                                          let bestUrl = "";
                                                                                                                                                                              if (ep.cdnList) {
                                                                                                                                                                                     for (const cdn of ep.cdnList) {
                                                                                                                                                                                                if (cdn.videoPathList?.length > 0) {
                                                                                                                                                                                                               // Ambil yang kualitasnya paling tinggi (sort desc)
                                                                                                                                                                                                                              const sorted = [...cdn.videoPathList].sort((a, b) => b.quality - a.quality);
                                                                                                                                                                                                                                             bestUrl = sorted[0].videoPath; 
                                                                                                                                                                                                                                                            break;
                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                      setVideoUrl(bestUrl);
                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                          if (loading) return <div className="h-screen bg-black flex items-center justify-center text-purple-500">Loading...</div>;
                                                                                                                                                                                                                                                                                            if (!detail) return <div className="h-screen bg-black text-white flex items-center justify-center">Drama Tidak Ditemukan (ID: {bookId})</div>;

                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                  <div className="min-h-screen bg-[#050505] text-white">
                                                                                                                                                                                                                                                                                                        {/* 1. PLAYER VIDEO */}
                                                                                                                                                                                                                                                                                                              <div className="sticky top-0 z-50 bg-black w-full border-b border-gray-800">
                                                                                                                                                                                                                                                                                                                      <div className="w-full aspect-video md:h-[60vh] bg-black flex items-center justify-center relative">
                                                                                                                                                                                                                                                                                                                                {videoUrl ? (
                                                                                                                                                                                                                                                                                                                                            <video 
                                                                                                                                                                                                                                                                                                                                                          key={videoUrl} 
                                                                                                                                                                                                                                                                                                                                                                        controls 
                                                                                                                                                                                                                                                                                                                                                                                      autoPlay 
                                                                                                                                                                                                                                                                                                                                                                                                    playsInline 
                                                                                                                                                                                                                                                                                                                                                                                                                  className="w-full h-full object-contain" 
                                                                                                                                                                                                                                                                                                                                                                                                                                poster={currentEp?.chapterImg}
                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <source src={videoUrl} type="video/mp4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </video>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="text-gray-500 flex flex-col items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Play className="w-12 h-12 opacity-50 mb-2"/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span>Pilih Episode untuk Memutar</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Tombol Back */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Link href="/" className="absolute top-4 left-4 bg-black/50 p-2 rounded-full backdrop-blur-sm z-50 hover:bg-purple-600 transition">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <ChevronLeft className="w-6 h-6 text-white" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* 2. INFO DRAMA */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="max-w-5xl mx-auto p-4 space-y-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h1 className="text-2xl font-bold mb-2">{detail.book?.bookName}</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex gap-2 mb-4 overflow-x-auto pb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {detail.book?.tags?.map(tag => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span key={tag} className="bg-gray-800 text-xs px-3 py-1 rounded-full whitespace-nowrap">{tag}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-gray-400 text-sm leading-relaxed line-clamp-3 bg-[#111] p-3 rounded-lg">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {detail.book?.introduction}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* 3. DAFTAR EPISODE */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="font-bold mb-4 flex items-center gap-2"><List className="w-5 h-5 text-purple-500"/> Semua Episode ({episodes.length})</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="grid grid-cols-5 sm:grid-cols-8 md:grid-cols-10 gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {episodes.map((ep) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              key={ep.chapterId}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => selectEpisode(ep)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className={`p-3 rounded-lg text-sm font-bold transition-all ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                currentEp?.chapterId === ep.chapterId 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ? 'bg-purple-600 text-white shadow-lg scale-105' 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : 'bg-[#1a1a1a] text-gray-400 hover:bg-[#252525]'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {ep.chapterIndex + 1}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          